### ISSUE TITLE
general question mode

### ISSUE THREAD

**Issue by shantanuo** [opensouls/terminal-copilot#40]
Please add a general question mode so that I do not have to leave the command mode! For e.g.

$> copilot -g "Who was the 23rd president?"
  Herbert Hoover 

ref: https://github.com/graiz/cbot

**Comment by 2mawi2** [comment]
Hey @shantanuo not sure if this is still in the scope of the current application ?

**Comment by JoelKronander** [comment]
hm, why not, can add it so it just becomes a quick way to send a general question.

**Comment by JoelKronander** [comment]
@shantanuo ok, finally added this, but under the -q flag.

```
copilot -q what is the best drink for late night coding
```
