### ISSUE TITLE
build_conversation should take usermessage=None as default input

### ISSUE THREAD

**Issue by jose-moran** [opensouls/terminal-copilot#49]
Referencing this:
https://github.com/opensouls/terminal-copilot/blob/50c1f6cd5cadbccc84b2d88a43501fac6e284152/copilot/messages_builder.py#L65

Running on MacOS with zsh and using Python 3.11. Typically, I get this:

```
❯ copilot list directory
Traceback (most recent call last):
  File "/Users/jmoran/anaconda3/bin/copilot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jmoran/anaconda3/lib/python3.11/site-packages/copilot/main.py", line 74, in main
    conversation = build_conversation(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: build_conversation() missing 1 required positional argument: 'usermessage'
```

But this is an easy fix: I imagine that the python version this was tested is <3.11. I suggest changing the function definition's first line to 
```python
def build_conversation(context: Context, usermessage: Optional[str]=None) -> Conversation:
```

which works fine for me (although I am not sure yet this doesn't break something else).

**Comment by hariveliki** [comment]
@jose-moran THX

**Comment by JoelKronander** [comment]
fixed by PR
