### ISSUE TITLE
Error message on Windows 11

### ISSUE THREAD

**Issue by EmpathicSage** [opensouls/terminal-copilot#51]
### Description
When invoking the `copilot` command-line option on a Windows 11 machine, a `TypeError` is raised indicating a missing argument for the function `build_conversation()`.

### Expected Behavior
Executing the `copilot` command should not produce any errors, and it should function as intended.

### Steps to Reproduce
1. Activate the virtual environment with `(.venv)`
2. Run the `copilot` command without the `-q` switch: `copilot list files`
3. Observe the error output

### Actual Behavior
Upon execution, the following error is displayed:

```PowerShell
(.venv) PS C:\Users\Owner\zgit\terminal-copilot> copilot list files
Traceback (most recent call last):
  File "C:\Users\Owner\zgit\terminal-copilot\.venv\Scripts\copilot-script.py", line 33, in <module>
    sys.exit(load_entry_point('terminal-copilot==1.4.0', 'console_scripts', 'copilot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\zgit\terminal-copilot\.venv\Lib\site-packages\terminal_copilot-1.4.0-py3.11.egg\copilot\main.py", line 74, in main
    conversation = build_conversation(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: build_conversation() missing 1 required positional argument: 'usermessage'
```

### Additional Observations
When using the `-q` switch, the error does not occur. For instance:

```PowerShell
(.venv) PS C:\Users\Owner\zgit\terminal-copilot> copilot -q hello copilot
> Hello! How can I assist you today?
Hello! How can I assist you today?
```

NOTE: Windows installation steps are slightly different from the documentation
- Instead of `source .venv/bin/activate` use `. .\.venv\Scripts\activate`
- Instead of `export OPENAI_API_KEY=<your key>`, use `$ENV:OPENAI_API_KEY = "YOUR_KEY"`

### Environment
- **OS:** Windows 11 Pro 22H2 22621.2428
- **Shell:** PowerShell 7.3.8
- **Python Version:** 3.11.6 (from Microsoft Store)
- **Commit:** 50c1f6cd5cadbccc84b2d88a43501fac6e284152 (HEAD -> main, tag: v1.4.0, origin/main, origin/HEAD)

**Comment by EmpathicSage** [comment]
Ahh, it seems we already have a similar issue mentioned here:

https://github.com/opensouls/terminal-copilot/issues/49

**Comment by JoelKronander** [comment]
I beleive this is now fixed. @EmpathicSage can you verify it works as expected now?
